import type { Metadata } from "next";

import "@/styles/globals.scss";

import { Lexend_Deca, Plus_Jakarta_Sans } from "next/font/google"
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import ApolloProvider from "@/providers/ApolloProvider";


const lexendDeca = Lexend_Deca({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-lexend-deca"
})

const plusJacartaSans = Plus_Jakarta_Sans({
    subsets: ["latin", "latin-ext"], 
    weight: ["400", "500", "600"],
    variable: "--font-plus-jacarta-sans"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ApolloProvider>
            <html lang="en">
                <body className={`${lexendDeca.variable} ${plusJacartaSans.variable}`}>
                    <div className="wrapper">
                        <Header/>
                        {children}
                        <Footer/>
                    </div>
                </body>
            </html>
        </ApolloProvider>
    );
}
